18 stat tests ks 20210923
appliedepi/epiRhandbook_jp pull request #12
Opened 2021-11-03 00:50 UTC by Kotomi-Sakai

completed

2021-11-17 11:42 UTC, ironwest requested changes
初回の翻訳、ありがとうございました。
レビューが遅くなって申し訳ありませんでした。

全体的にですが、
　・原文にない位置での改行
　・統計手法などをカタカナで記載いただいていますが、英語で記載いただきたい
の2点が数が多かったため指摘してきれていないかもしれません。

上記とコメントにつきまして、ご対応いただけますと幸甚です。

2021-11-17 11:42 UTC, ironwest commented on new_pages/stat_tests.Rmd
> +また，t
改行はなしでおねがいします。

2021-11-17 11:42 UTC, ironwest commented on new_pages/stat_tests.Rmd
> +### T 検定
{}をつけてください。

2021-11-17 11:42 UTC, ironwest commented on new_pages/stat_tests.Rmd
> +###  {.unnumbered}
次の###の後ろにつけてください。

2021-11-17 11:42 UTC, ironwest commented on new_pages/stat_tests.Rmd
> +### ウィルコクソンの順位和検定
検定の名前は英語でお願いします。

2021-11-17 11:42 UTC, ironwest commented on new_pages/stat_tests.Rmd
> +2つのグループにおける連続変数の分布を比較します。デフォルトでは、2つのグループを比較する際にウィルコクソンの順位和検定と中央値（四分位範囲）を使用します。しかし、非正規分布のデータや複数のグループを比較する場合は、クラスカルーウォリス検定を使用することがより適切です。
検定名は英語でお願いします。

2021-11-17 11:42 UTC, ironwest commented on new_pages/stat_tests.Rmd
> +### クラスカルーウォリス検定
カタカナを英語にしてください。また、{}を追加してください。

2021-11-17 11:42 UTC, ironwest commented on new_pages/stat_tests.Rmd
> +データが正規分布しているかどうかに関わらず、2つ以上のグループにおける連続変数の分布を比較する。
比較する　→　比較します　でお願いします。

2021-11-17 11:42 UTC, ironwest commented on new_pages/stat_tests.Rmd
> +数値変数間の相関は、**tidyversecorrr**
原文では、　**tidyverse** 改行 **corr**
となっているのでそのようにお願いできますでしょうか？

2021-11-18 12:28 UTC, Kotomi-Sakai commented on new_pages/stat_tests.Rmd
> +このページでは、**base** R、**rstatix**、**gtsummary**
行をどのように1つにするのか方法がわかりませんでした

2021-11-18 12:30 UTC, Kotomi-Sakai commented on new_pages/stat_tests.Rmd
> +## **準備**
{}が何のことなのかがわかりませんでした

2021-11-18 12:30 UTC, Kotomi-Sakai commented on new_pages/stat_tests.Rmd
> +数値変数間の相関は、**tidyversecorrr**
改行ボタンをおしても、なぜか元に位置に戻ってしまいます

2021-11-18 12:33 UTC, Kotomi-Sakai commented on new_pages/stat_tests.Rmd
> +このページでは、**base** R、**rstatix**、**gtsummary**
改行の件ですが、元の文をどのようにRで確認していいかわからず、WEBで公開されているものをみたのですが、自分の翻訳とのズレをどのように確認していいかがわかりませんでした

2021-11-18 12:35 UTC, Kotomi-Sakai commented on new_pages/stat_tests.Rmd
> +-   T 検定\
削除できたと思います。visual modeで翻訳をしていたのですが、visualだと/や{}などの記載に気づきませんでした

2022-03-10 21:32 UTC, ironwest approved these changes

2022-03-10 21:32 UTC, merged