23 time series sn 20210923
appliedepi/epiRhandbook_jp pull request #26
Opened 2021-12-15 16:54 UTC by Seito-N

西田さん、

23章担当の中村です。
担当分の翻訳が完了しましたので、レビューをお願いします。
何かと至らない点もあるかと存じますが、何卒よろしくお願いいたします。

中村

2021-12-17 09:27 UTC, ironwest requested changes
レビューと同時にtypoや改行などを修正してコミットしてあります。

前のコミット直前コメント等をご確認いただけますと幸いです。

2021-12-29 08:11 UTC, Seito-N commented on new_pages/time_series.Rmd
> +
ここは英文の削除漏れでした。ご確認ありがとうございます。

2021-12-29 13:16 UTC, Seito-N commented on new_pages/time_series.Rmd
> +以下のコードは、日付カラムが適切なフォーマットであることを確認します。このタブでは **tsibble** パッケージを使用し、 `yearweek` 関数が暦週変数を作成するために使用されています。他にもいくつかの方法がありますが（詳細は[Working with dates](https://epirhandbook.com/working-with-dates.html)のページを参照して
修正しました。

2021-12-29 13:17 UTC, Seito-N commented on new_pages/time_series.Rmd
> +上記の簡単な検査では見逃しがないことを確認しましたが、新年頃に報告が遅れる問題があるようにも見えました。この問題に対処する1つの方法は、これらの値を欠損に設定して値を入力することです。時系列入力の最も簡単な方法は、最新の非欠損値と次の非欠損値の間に直線を引くことです。これを行うために， **imputeTS** パッケージの関数`na_interpolation()` を使用します．
修正しました。

2021-12-29 13:23 UTC, Seito-N commented on new_pages/time_series.Rmd
> +フーリエ列はリストなので（そのため個別に名前がついていない）、 *N.b.* 行を結合するには、（Tidyverse の `bind_rows` ではなく） `rbind()` を使用しなければなりません。
すべてフーリエ項として翻訳していたので、フーリエ列に修正しました。

2022-03-16 09:07 UTC, ironwest approved these changes

2022-03-16 09:09 UTC, merged