first draft
appliedepi/epiRhandbook_jp pull request #36
Opened 2021-12-28 10:07 UTC by ShuntaroS

The translation of this section is completed and ready to be merged.

2022-01-06 08:58 UTC, ironwest commented on new_pages/regression.Rmd
> +下のコード中の式において、応答と説明変数の列名はチルダで分けられている。またデータセットは `data =` で設定している。モデルの結果を R オブジェクトとして定義し、後で使用します。
提案：
式を応答と説明変数の列名をチルダ（~）で分けた formula として与え、利用するデータを `data = `で指定しましょう。後で利用するために、実行結果のモデルを R オブジェクトとして定義しておきます。

2022-01-06 08:59 UTC, ironwest commented on new_pages/regression.Rmd
> +次に、モデルの結果に対して `summary()` を実行すると、回帰係数（推定値）、P 値、残差などの統計指標を確認することができます。
提案；
そうすると、`summary()` をモデルの結果に対して実行することができ、回帰係数（推定値）、P 値、残差などの統計指標を確認することができます。

2022-01-06 09:59 UTC, ironwest requested changes
レビュー行いました。日本語表現の部分で微妙に気になったところを中心にコメントしています（細かな修正はこちらで行っております）

お忙しいところ申し訳ありませんが、ご確認ください。

2022-01-06 09:59 UTC, ironwest commented on new_pages/regression.Rmd
> +この例では、異なる年齢カテゴリと死亡というアウトカム（準備セクションで 1 とコードした）との関連を評価しています。以下は、`age_cat` によるアウトカムの単変量モデルです。モデルの出力を `model` として保存し、`summary()` でコンソールに出力します。出力される推定値は[対数オッズ比]{.ul}であり、ベースラインレベルは `age_cat` の 1 番目の因子レベル（"
レベルである　→　レベルです。

2022-03-10 21:40 UTC, ironwest approved these changes

2022-03-11 09:34 UTC, ironwest commented
add change
```diff
* Unmerged path .DS_Store
diff --git a/new_pages/stat_tests.Rmd b/new_pages/stat_tests.Rmd
index 43bec74..a5725ee 100644
--- a/new_pages/stat_tests.Rmd
+++ b/new_pages/stat_tests.Rmd
@@ -1,167 +1,153 @@
-# Simple statistical tests { }
+# 基本的な統計的検定 { #stat-tests }
 
+この章では、**base**R、**rstatix**、**gtsummary** を使って、基本的な統計的検定を行う方法を紹介します。
 
-This page demonstrates how to conduct simple statistical tests using **base** R, **rstatix**, and **gtsummary**.  
+-   T 検定
+-   Shapiro-Wilk 検定
+-   Wilcoxon の順位和検定
+-   Kruskal-Wallis 検定
+-   カイ二乗検定
+-   数値変数間の相関
 
-* T-test  
-* Shapiro-Wilk test  
-* Wilcoxon rank sum test  
-* Kruskal-Wallis test  
-* Chi-squared test  
-* Correlations between numeric variables  
+...他にも様々な検定を行うことができますが、ここでは一般的なものだけを紹介し、それ以外のものにはドキュメントへのリンクを張っています。
 
-...many other tests can be performed, but we showcase just these common ones and link to further documentation.  
+上記の各パッケージには、それぞれ利点と欠点があります：
 
-Each of the above packages bring certain advantages and disadvantages:  
-
-* Use **base** R functions to print a statistical outputs to the R Console  
-* Use **rstatix** functions to return results in a data frame, or if you want tests to run by group  
-* Use **gtsummary** if you want to quickly print publication-ready tables  
+-   **base** R の関数を使用して、R コンソールに統計的な出力を表示します。
 
+-   データフレームで結果を表示する場合や、グループごとに検定を実行したい場合は、**rstatix** パッケージの関数を使用します。
 
+-   出版用の表を素早く表示したい場合は、**gtsummary** を使用します。
 
 <!-- ======================================================= -->
-## Preparation {  }
-
 
-### Load packages {.unnumbered}
+## 準備
 
-This code chunk shows the loading of packages required for the analyses. In this handbook we emphasize `p_load()` from **pacman**, which installs the package if necessary *and* loads it for use. You can also load installed packages with  `library()` from **base** R. See the page on [R basics] for more information on R packages.  
+### パッケージを読み込む {.unnumbered}
 
+以下のコードを実行すると、分析に必要なパッケージが読み込まれます。このハンドブックでは、パッケージを読み込むために、pacman パッケージの p_load() を主に使用しています。p_load() は、必要に応じてパッケージをインストールし、現在の R セッションで使用するためにパッケージを読み込む関数です。また、すでにインストールされたパッケージは、R の基本パッケージである base の library() を使用して読み込むこともできます。R のパッケージに関する詳細は [R basics](#basics) の章をご覧ください。
 
 ```{r}
 pacman::p_load(
-  rio,          # File import
-  here,         # File locator
-  skimr,        # get overview of data
-  tidyverse,    # data management + ggplot2 graphics, 
-  gtsummary,    # summary statistics and tests
-  rstatix,      # statistics
-  corrr,        # correlation analayis for numeric variables
-  janitor,      # adding totals and percents to tables
-  flextable     # converting tables to HTML
+  rio,          # ファイルをインポートする
+  here,         # ファイルの位置決める
+  skimr,        # データの概要を把握する
+  tidyverse,    # データ管理 + ggplot2 グラフィックス 
+  gtsummary,    # 要約統計と検定をする
+  rstatix,      # 統計を行う
+  corrr,        # 数値変数の相関分析を行う
+  janitor,      # 表に合計値とパーセンテージを加える
+  flextable     # 表をHTMLに変換する
   )
 ```
 
-### Import data {.unnumbered}
-
-We import the dataset of cases from a simulated Ebola epidemic. If you want to follow along, <a href='https://github.com/epirhandbook/Epi_R_handbook/raw/master/data/case_linelists/linelist_cleaned.rds' class='download-button'>click to download the "clean" linelist</a> (as .rds file). Import your data with the `import()` function from the **rio** package (it accepts many file types like .xlsx, .rds, .csv - see the [Import and export] page for details).  
+### データをインポートする
 
+エボラ出血熱の流行をシミュレートしたデータセットをインポートします。お手元の環境でこの章の内容を実行したい方は、 <a href='https://github.com/epirhandbook/Epi_R_handbook/raw/master/data/case_linelists/linelist_cleaned.rds' class='download-button'>クリック</a>して「前処理された」ラインリスト（linelist）データをダウンロードしてください>（.rds 形式で取得できます）。データは **rio** パッケージの `import()` を利用してインポートしましょう（**rio** パッケージは、.xlsx、.csv、.rds など様々な種類のファイルを取り扱うことができます。詳細は、[インポートとエクスポート](#importing) の章をご覧ください。）
 
 ```{r, echo=F}
-# import the linelist into R
+# linelist を R にインポートする
 linelist <- rio::import(here::here("data", "case_linelists", "linelist_cleaned.rds"))
 ```
 
 ```{r, eval=F}
-# import the linelist
+# linelist のインポートをする
 linelist <- import("linelist_cleaned.rds")
 ```
 
-The first 50 rows of the linelist are displayed below.
+linelist の最初の50行が下のように表示されます。
 
 ```{r, message=FALSE, echo=F}
-# display the linelist data as a table
+# linelist のデータをテーブルとして表示する
 DT::datatable(head(linelist, 50), rownames = FALSE, filter="top", options = list(pageLength = 5, scrollX=T), class = 'white-space: nowrap' )
 ```
 
+## base R
 
+**base** R の関数を使って、統計的検定を行うことができます。コマンドは比較的簡単で、結果は R のコンソールに表示されるので簡単に見ることができます。しかし、出力は、通常、リストですので、結果を次の操作で使用したい場合は、操作が難しくなります。
 
+### T 検定
 
+「スチューデントの t 検定」とも呼ばれる[ｔ検定](https://en.wikipedia.org/wiki/Student%27s_t-test)は、通常、2つのグループ間で何らかの数値変数の平均値に有意差があるかどうかを判定するために使用されます。ここでは、列が同じデータフレーム内にあるかどうかに応じて、この検定を行うための構文を示します。
 
-## **base** R {}
-
-You can use **base** R functions to conduct statistical tests. The commands are relatively simple and results will print to the R Console for simple viewing. However, the outputs are usually lists and so are harder to manipulate if you want to use the results in subsequent operations. 
-
-### T-tests {.unnumbered} 
-
-A [t-test](https://en.wikipedia.org/wiki/Student%27s_t-test), also called "Student's t-Test", is typically used to determine if there is a significant difference between the means of some numeric variable between two groups. Here we'll show the syntax to do this test depending on whether the columns are in the same data frame.
-
-**Syntax 1:** This is the syntax when your numeric and categorical columns are in the same data frame. Provide the numeric column on the left side of the equation and the categorical column on the right side. Specify the dataset to `data = `. Optionally, set `paired = TRUE`, and `conf.level = ` (0.95 default), and `alternative = ` (either "two.sided", "less", or "greater"). Enter `?t.test` for more details.  
+構文1：これは、数値列とカテゴリー列が同じデータフレームにある場合の構文です。数式の左側に数値列を、右側にカテゴリー列を用意します。データセットを `data =`で指定します。オプションとして、`paired = TRUE`、`conf.level =` (初期設定は0.95)、`alternative =` ("two.sided"、 "less"、 "greater" のいずれか)を設定します。詳細を知りたい場合は `?t.test` と入力してください。
 
 ```{r}
-## compare mean age by outcome group with a t-test
+##ｔ検定を使用してアウトカムグループごとに平均年齢を比較する
 t.test(age_years ~ gender, data = linelist)
 ```
 
-**Syntax 2:** You can compare two separate numeric vectors using this alternative syntax. For example, if the two columns are in different data sets.  
+構文2：この代替構文を使って、2つの別々の数値ベクトルを比較することができます。たとえば、2 つの列が異なるデータセットにある場合です。
 
 ```{r, eval=F}
 t.test(df1$age_years, df2$age_years)
 ```
 
-You can also use a t-test to determine whether a sample mean is significantly different from some specific value. Here we conduct a one-sample t-test with the known/hypothesized population mean as `mu = `:  
+また，t 検定は，標本平均がある特定の値と有意に異なるかどうかを判定するためにも使用できます。ここでは、既知/仮説の母平均を `mu =`として、1標本の t 検定を行います。
 
 ```{r, eval=F}
 t.test(linelist$age_years, mu = 45)
 ```
 
-### Shapiro-Wilk test {.unnumbered}  
-
-The [Shapiro-Wilk test](https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test) can be used to determine whether a sample came from a normally-distributed population (an assumption of many other tests and analysis, such as the t-test). However, this can only be used on a sample between 3 and 5000 observations. For larger samples a [quantile-quantile plot](https://ggplot2.tidyverse.org/reference/geom_qq.html) may be helpful. 
+### Shapiro-Wilk 検定
 
+[Shapiro-Wilk 検定](https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test)は，標本が正規分布の母集団から得られたものであるかどうかを判定するために使用できます（t 検定など，他の多くの検定や分析の仮定）．ただし，これは3件から5000件まで観察サンプルにしか使用できません。より大きなサンプルでは，[分位数-分位数 プロット](https://ggplot2.tidyverse.org/reference/geom_qq.html)を使用することが有用かもしれません。
 
 ```{r, eval=F}
 shapiro.test(linelist$age_years)
 ```
 
-### Wilcoxon rank sum test {.unnumbered}
+### Wilcoxon の順位和検定
 
-The Wilcoxon rank sum test, also called the [Mann–Whitney U test](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test), is often used to help determine if two num [...]

2022-07-21 11:54 UTC, ysaito8015 reviewed
@ironwest 
@ShuntaroS 
各位
意図せず変更されたファイルが push されているため、いったん PR をクローズし改めて PR を作成します。

2022-08-03 06:38 UTC, ysaito8015 commented on new_pages/regression.Rmd
> +下のコード中の式において、応答と説明変数の列名はチルダで分けられている。またデータセットは `data =` で設定している。モデルの結果を R オブジェクトとして定義し、後で使用します。
確認しました

2022-08-03 06:38 UTC, ysaito8015 commented on new_pages/regression.Rmd
> +次に、モデルの結果に対して `summary()` を実行すると、回帰係数（推定値）、P 値、残差などの統計指標を確認することができます。
反映されていることを確認しました

2022-08-03 06:39 UTC, ysaito8015 commented on new_pages/regression.Rmd
> +この例では、異なる年齢カテゴリと死亡というアウトカム（準備セクションで 1 とコードした）との関連を評価しています。以下は、`age_cat` によるアウトカムの単変量モデルです。モデルの出力を `model` として保存し、`summary()` でコンソールに出力します。出力される推定値は[対数オッズ比]{.ul}であり、ベースラインレベルは `age_cat` の 1 番目の因子レベル（"
反映しました

2022-08-03 06:40 UTC, closed without merging