25 contact tracing hk 20210923
appliedepi/epiRhandbook_jp pull request #48
Opened 2022-01-07 05:08 UTC by hitomik723

My apologies for the delay - this chapter is ready for review. Thank you!

2022-01-18 21:22 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +この章で扱う内容は、他の章で取り扱われているデータ管理と可視化の基礎（データ前処理や整備、表の作り方や、時系列分析など）を参照していますが、その中でも特に、実地疫学調査の業務的意思決定に役立つ接触者追跡データに特有の例を取り上げます。例えば、接触者追跡データを時系列や地域ごとに可視化する図や、接触者追跡調査の責任者に報告するための重要業績評価指標（Key Performance Indicato
この章で扱う内容は、他の章で取り扱われているデータ管理と可視化の基礎（データ前処理や整備、表の作り方や、時系列分析など）を参照していますが、その中でも特に、業務における意思決定に役立つ追跡データに特有の例を取り上げます。例えば、追跡データを時系列や地域ごとに可視化する図や、調査の責任者に報告するための重要業績評価指標（Key Performance Indicator: KPI）の表などを作成します。

2022-01-18 21:23 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +本章では、[Go.Data](https://www.who.int/tools/godata) プロジェクトのウェブサイトからダウンロードできる接触者追跡データを例として使用しますが、本章で扱う内容は、他のウェブサイトから取得した接触者追跡データを使用しても再現可能です。その場合は、データの構造によって、必要な前処理が異なる可能性があります。
以下、接触者追跡データ　を　追跡データ　と記述します

2022-01-18 21:24 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +### データをインポートする {.unnumbered}
データのインポート

2022-01-18 21:25 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +  <span>接触者追跡記録のサンプルデータ （.rds file） </span>
接触者追跡記録のサンプルデータ（.rds ファイル）

2022-01-18 21:28 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +#### 感染者登録のデータ {.unnumbered}
Case data なので、「感染症例データ」などがより適しているきがします

2022-01-18 21:30 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +#### 接触者登録のデータ {.unnumbered}
Contact data　なので、　接触者のデータなどがよりわかりやすいかと思います（登録という文字をあえて入れないほうがよいかと感じました。）

2022-01-18 21:33 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +このサンプルデータセットには、接触者の連絡先と、接触者追跡調査で必要となる多くの情報が含まれています。以下のコードを実行する際も、ファイルパスを指定してください。データをインポート後、次の順で、データクリーニングを行います。
このデータは、接触にかかわる情報が含まれた表です。以下のコードを実行する際も、あなたの環境にそったファイルパスを指定してください。データをインポートした後、次の順で、データクリーニングを行います。

2022-01-18 21:34 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +* 特定の列のみを選択し、選択した列のうち1つの列の名前を変更する\
* 特定の列のみを選択しつつ、1 つの列名を変更する

2022-01-18 21:40 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +#### 接触者追跡調査のデータ {.unnumbered}
フォローアップデータ

2022-01-18 21:55 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +最後に、感染者と接触者の関連についてのデータをインポートし、特定の列のみを残します。
ここでは、感染症例と接触の関係性を表すデータをインポートします。表示する列を絞り込んでおきましょう。

2022-01-18 21:56 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +以下では、インポートしたデータの最初の `50` 人を表示しています。感染者と接触者の関連についてのあらゆる情報が含まれています。
以下は、「関連データ」の最初の50行です。感染症例と接触の関係がすべて含まれています。

2022-01-18 22:02 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +他にも、感染者と接触者両方の年齢が含まれている Go.Data の感染者と接触者の関連データ（`relationships` データセット）を使用すると、感染者と接触者の年齢層の違いを表す人口ピラミッドを作成することもできます。感染者と接触者の関連データ人口ピラミッドを作成する場合は、年齢変数をカテゴリー化し、数値型から因子（ファクタ）型にする必要があります（詳しくは、 [データクリーニングと主
Go.Data の感染者と接触者の関連データ（`relationships` データセット）には、感染者と接触者両方の年齢が含まれています。そのため、このデータセットを利用して、二つの集団の年齢層の違いを表す人口ピラミッドを作成することもできます。`relationships` データセットの年齢を含む数字型の列を因子型に変更しています。（詳しくは、 [データクリーニングと主要関数] (#cleaning) の章を参照ください）。また、**ggplot2** で図をプロットしやすくするために、データを縦型（long型）に変換する必要があります（詳細は、 [データの縦横変換] (#pivoting) をご覧ください）。

2022-01-19 22:30 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +前処理した感染者と接触者の関連データ（`relationships` データセット）を使用し、先ほどと同じように `age_pyramid()` 関数を使用して人口ピラミッドをプロットしてみましょう。ただし、 `gender` 変数を使用するのではなく、 `category` 変数（感染者か接触者のどちらであるかを示す変数）を使用する必要があります。
コメント：申し訳ありません、せっかく詳しく翻訳いただいているのですが、原文になるべく忠実に翻訳してほしいと、大元からリクエストをいただいているため、（）などでの追記部分はなるべく反映する形ですこし形を整えさせていいただきました。（他の部分も同様です）

2022-01-19 22:34 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +前処理した感染者と接触者の関連データ（`relationships` データセット）を使用し、先ほどと同じように `age_pyramid()` 関数を使用して人口ピラミッドをプロットしてみましょう。ただし、 `gender` 変数を使用するのではなく、 `category` 変数（感染者か接触者のどちらであるかを示す変数）を使用する必要があります。
提案：これで、前と同様に変換したデータを `age_pyramid()` で図として描画することができます。ただし、`gender` 変数ではなく、`category`（接触者か感染者のどちらか）で置き換えてあります。

2022-01-23 21:48 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +他にも、感染者の職業の内訳などの特徴も可視化することができます。（ここでは、感染者登録のデータ（`cases` のデータセット）を使用し、円グラフを作成します。）
他にも、感染者の職業の内訳などの特徴も可視化することができます（例えば、円グラフなどの形です）。

2022-01-23 21:55 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +  mutate(occupation = forcats::fct_explicit_na(occupation),  # 欠損値を可視化する（NA を (Missing) と表示させる）
NA をカテゴリーとする

2022-01-23 21:56 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +         occupation = forcats::fct_infreq(occupation)) %>%   # 職業変数を、職業ごとの感染者数で多い方から順に並び替える
頻度順で因子型のレベルを並べかえる

2022-01-23 22:00 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +#### 接触者登録のデータ {.unnumbered}
後半の内容を確認してから改めて記載していますが、このデータ、後々参照される回数が多いので、「接触者（Contact）データ」と統一させてください。

2022-01-23 22:01 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +#### 接触者追跡調査のデータ {.unnumbered}
後半の内容を確認してから改めて記載していますが、このデータ、後々参照される回数が多いので、「追跡（Follow-up）データ」と統一させてください。

2022-01-23 22:01 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +#### 感染者と接触者の関連データ {.unnumbered}
後半の内容を確認してから改めて記載していますが、このデータ、後々参照される回数が多いので、「関連（Relationships）データ」と統一させてください。

2022-01-23 22:02 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +データ構造にもよりますが、すべての感染者と接触者を含むデータセットがあれば、感染者一人当たりの接触者数を算出し、評価を行うことができます。Go.Data のデータでは、感染者と接触者の関連データ（`relationships` データセット）に、感染者（`sources`）と接触者（`targets`）の関連に関する情報が含まれています。
データ構造にもよりますが、すべての感染者と接触者を含むデータセットがあれば、感染者一人当たりの接触者数を算出し、評価を行うことができます。Go.Data のデータでは、関連（relationships） データに、感染者（"sources"）と接触者（"targets"）の関連に関する情報が含まれています。

2022-01-23 22:07 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +感染者と接触者の関連データ（`relationships` データセット）では、各行が接触者の記録を示し、感染元となった感染者についての情報が記載されています。このデータセットには、複数の感染者と関連している接触者はありませんが、もし複数の感染者と関連している接触者がいる場合には、そのような接触者データを精査し、事前に処理を行う必要があります。（この章では触れていません。）
このデータセットでは、各行が接触者の記録を示し、感染元となった感染者についての情報が記載されています。複数の感染者と関連している接触者はありませんが、もし複数の感染者と関連している接触者がいる場合には、そのような接触者データを精査し、事前に処理を行う必要があります。（訳者中：この章では触れていません。）

2022-01-24 21:40 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +[[**注意点**]{.ul}***:*** 接触者調査（フォローアップ）に関するデータを扱う際は、重複した調査記録に注意してください。ある接触者に対し、同じ日に複数の調査（フォローアップ）が誤って行われる可能性があります。例えば、調査員が接触者と連絡がとれなかった際にその記録を午前中に提出し、後に連絡できた際に 2 つ目の記録を提出することが起こりえます。重複した記録をどのように処理するかにつ
接触者調査（フォローアップ）に関するデータを扱う際は、重複した調査記録に注意してください。ある接触者に対し、同じ日に複数の調査（フォローアップ）が誤って行われる可能性があります。これは一概には間違いといえず、現実を反映している場合もあります。例えば、調査員が接触者と連絡がとれなかった際にその記録を午前中に提出し、後に連絡できた際に 2 つ目の記録を提出するような場合です。重複した記録をどのように処理するかについては、調査の運用状況によりますが、重複記録を含んだデータを提示する際は、重複記録をどのように処理したかを明確に記載してください。

2022-01-24 21:47 UTC, ironwest commented on new_pages/contact_tracing.Rmd
> +日付データは連続しているため、`date_of_followup` を x 軸に指定したヒストグラムを使用し、接触者追跡調査のデータ（`followups`のデータセット）を時系列でプロットできます。`aes()` 関数内の `fill =` 引数に `followup_status` 変数を指定することで、「積み上げ型」のヒストグラムを作成し、`labs()` 関数内の `fill =` 引数
日付データは連続した数値であるため、`date_of_followup` を x 軸に指定したヒストグラムを使用し、接触者追跡調査のデータ（`followups`のデータセット）を時系列でプロットします。積み上げ型のヒストグラムを、`aes()` 内の `fill =` 引数に `followup_status` 変数を指定することで作成します。また、`labs()` 関数内の `fill =` 引数を使用して凡例のタイトルを作成することができます。

2022-03-16 22:01 UTC, ironwest requested changes
すいません！１月のコメントを付けた部分を反映するかご検討いただけますでしょうか？（git上のコメントでfinish revisionとつけてしまいましたが無視してください）

2022-07-16 04:16 UTC, hitomik723 commented on new_pages/contact_tracing.Rmd
> +#### 感染者登録のデータ {.unnumbered}
ありがとうございます、ご提案の通り「感染症例データ」とし、初出のみ「感染症例データ（`cases` データセット）」としました。

2022-07-16 04:17 UTC, hitomik723 commented on new_pages/contact_tracing.Rmd
> +この章では、実地疫学調査で収集された接触者追跡データの記述統計を行い、接触者追跡データを分析する際に考慮すべき重要事項、ならびに課題に直面した時の対処法を説明します。
ありがとうございます、ご提案の通り短縮しました。

2022-07-16 04:17 UTC, hitomik723 commented on new_pages/contact_tracing.Rmd
> +#### 接触者登録のデータ {.unnumbered}
ありがとうございます、ご提案の通り「接触者データ」とし、初出のみ「接触者データ（`contacts` データセット）」としました。

2022-07-16 04:18 UTC, hitomik723 commented on new_pages/contact_tracing.Rmd
> +#### 接触者追跡調査のデータ {.unnumbered}
ありがとうございます、ご提案の通り「追跡データ」とし、初出のみ「追跡データ（`followups` データセット）」としました。

2022-07-16 04:23 UTC, hitomik723 commented on new_pages/contact_tracing.Rmd
> +#### 感染者と接触者の関連データ {.unnumbered}
ありがとうございます、ご提案の通り「関連データ（`relationships` データセット）」で統一しました。

2022-07-16 04:31 UTC, hitomik723 reviewed
@ironwest 対応が遅くなり大変申し訳ありません。頂いたすべてのコメントを反映し、修正しました。最終確認後、マージをお願いできますでしょうか？お忙しければ私の方で対応します。遅くなり本当に申し訳ありません。

2022-07-17 04:41 UTC, merged