28 gis yb 20210923
appliedepi/epiRhandbook_jp pull request #51
Opened 2022-01-13 02:08 UTC by babayoshihiko

The chapter for geographical information system has been completed.

Sorry about the delay. I thought I had sent q pull request.

2022-02-01 22:33 UTC, ironwest commented on new_pages/gis.Rmd
> +一般的な GIS ソフトウェアの中には、ポイント＆クリックで地図の作成や空間分析ができるものがあります。これらのツールには、コードを覚える必要がない、アイコンや機能を手動で選択して地図上に配置するのが簡単であるなどの利点があります。ここでは、人気のある2つのソフトウェアを紹介します。
提案：ポイント＆クリック　→　マウス操作

2022-02-01 22:34 UTC, ironwest commented on new_pages/gis.Rmd
> +R を GIS として使用することは、「ポイント＆クリック」ではなく「コマンドライン・インターフェース」（目的の結果を得るためにはコーディングが必要）であるため、最初は敷居が高く感じられるかもしれません。しかし、繰り返し地図を作成したり、再現性のある分析を行う必要がある場合には、これは大きな利点となります。
R を GIS として使用することは、「マウス操作」ではなく「コマンドライン・インターフェース」（目的の結果を得るためにはコーディングが必要）を利用した操作が必要であるため、最初は敷居が高く感じられるかもしれません。しかし、繰り返し地図を作成したり、再現性のある分析を行う必要がある場合には、これは大きな利点となります。

2022-02-01 22:36 UTC, ironwest commented on new_pages/gis.Rmd
> +**ベクトルデータ** - GIS で使用される空間データの最も一般的な形式であるベクトルデータは、頂点とパスの幾何学的なフィーチャ (feature; 「地物」とも訳される) で構成されています。ベクトルデータは、さらに3つのタイプに分類され、広く使用されています。
**ベクトルデータ** - GIS で使用される空間データの最も一般的な形式です。ベクトルデータは、頂点とパスの幾何学的なフィーチャ (feature; 「地物」とも訳される) で構成されています。ベクトルの空間データは、さらに3つの広く使用されるタイプに分類されます。

2022-02-01 22:39 UTC, ironwest commented on new_pages/gis.Rmd
> +  * <u>ポリゴン</u> - ポリゴンは、点で接続された少なくとも3つの線分で構成されています。ポリゴンのフィーチャは、面積だけでなく、長さ（すなわち、面積の周囲）を持っています。ポリゴンは、地域（例：村）や構造（例：病院の実際の面積）を示すときに使用されます。
* <u>ポリゴン</u> - ポリゴンは、点で接続された少なくとも3つの線分で構成されています。ポリゴンのフィーチャは、面積だけでなく、長さ（すなわち、面積の外周の長さ）を持っています。ポリゴンは、地域（例：村）や構造（例：病院の実際の面積）を示すときに使用されます。

2022-02-01 22:40 UTC, ironwest commented on new_pages/gis.Rmd
> +### 空間データを可視化 {.unnumbered}
空間データの可視化

2022-02-02 21:29 UTC, ironwest commented on new_pages/gis.Rmd
> +  * <u>座標系 (Coordinate System)</u> - 多くの異なる座標系があるので、自分の座標がどのシステムから来ているかを確認してください。緯度/経度の度数は一般的ですが、[UTM](https://www.maptools.com/tutorials/utm/quick_guide)座標を見ることもできます。
* <u>座標系 (Coordinate System)</u> - 非常にたくさんの座標系があるため、自分が使用する座標がどの座標系を用いているのかを必ず確認してください。緯度/経度の度数を用いたものは一般的ですが、[UTM](https://www.maptools.com/tutorials/utm/quick_guide)座標が利用されていることもあります。

2022-02-02 21:30 UTC, ironwest commented on new_pages/gis.Rmd
> +  * <u>単位 (Units)</u> - 座標系の単位を知ることができます（例：10進法の度、メートル）。
* <u>単位 (Units)</u> - 座標系の単位を知ることができます（例：小数点で表された度、メートル）。

2022-02-02 21:33 UTC, ironwest commented on new_pages/gis.Rmd
> +  * <u>測地系 (Datum)</u> - 地球上の特定のモデルです。測地系は長年にわたって改訂されてきたので、マップレイヤーが同じ測地系を使用していることを確認してください。
* <u>測地系 (Datum)</u> - 地球をモデル化したものの、特定のバージョンを指します。測地系は長年にわたって改訂されてきたので、地図として表示されるレイヤー（マップレイヤー）が同じ測地系を使用していることを確認してください。

2022-02-02 21:34 UTC, ironwest commented on new_pages/gis.Rmd
> +  * <u>投影 (Projection)</u> - 丸い地球を平らな表面（地図）に投影するために使用された数式への参照。
* <u>投影 (Projection)</u> - 実際には丸い地球を平らな表面（地図）に投影するために使用された数式への参照。

2022-02-02 21:37 UTC, ironwest commented on new_pages/gis.Rmd
> +<!-- 訳注: 日本の主な CRS
訳注：日本の主な CRS は次のようなものがあります。<!--Translator Note: CRS commonly used in Japan are following:>

2022-02-02 21:41 UTC, ironwest commented on new_pages/gis.Rmd
訳注の内容、後ほど原文の著者の方からチェックが入るため、英語をコメントで追記してあります。（直接記載する形にしています）

2022-02-02 21:43 UTC, ironwest commented on new_pages/gis.Rmd
> +地図を作るためには、以下の通り、必要な重要アイテムがあります。
地図を作るためには、以下の通り、いくつかの重要な要素について、考え、また入手しなければありません。

2022-02-02 21:45 UTC, ironwest commented on new_pages/gis.Rmd
> +    + 事前に定義された地理的境界線（例えば、行政区域）を扱う場合、参照シェープファイルは、政府機関やデータ共有組織から自由にダウンロードできることが多い。迷ったときは、「[地域名] shapefile」でググってみるといいでしょう。
+ 事前に定義された地理的境界線（例えば、行政区域）を扱う場合、参照シェープファイルは、政府機関やデータ共有組織から自由にダウンロードできることが多いです。迷ったときは、「[地域名] shapefile」とグーグルで検索してみるとよいでしょう。

2022-02-02 21:46 UTC, ironwest commented on new_pages/gis.Rmd
> +    + 住所情報はあっても緯度・経度がないような場合は、 **ジオコーディング・エンジン** を使ってデータの空間参照データを取得する必要があるかもしれません。
+ 住所情報はあっても緯度・経度がないような場合は、 **ジオコーディング・エンジン**（**geocoding engine**）を使ってデータの空間参照データを取得する必要があるかもしれません。

2022-02-03 09:29 UTC, ironwest commented on new_pages/gis.Rmd
> +1) シェープファイルをインポート
1) シェープファイルをインポートする

2022-02-03 09:29 UTC, ironwest commented on new_pages/gis.Rmd
> +2) 列名をクリーンアップ
2) 列名を加工する

2022-02-03 09:29 UTC, ironwest commented on new_pages/gis.Rmd
> +3) 興味のあるエリアだけを残すために行をフィルターする
3) 興味のある地域だけを残すために行を抽出する

2022-02-03 09:31 UTC, ironwest commented on new_pages/gis.Rmd
> +シェープファイルをインポートするには、**sf** の `read_sf()` 関数を使います。ファイルのパスは `here()` で与えられます。- ここでは、Rプロジェクトの "data"、"gis"、"shp" というサブフォルダにファイル名 "sle_adm3.shp" として格納されています（詳細は [import and export] と [R Projects] のページを参照し
シェープファイルをインポートするには、**sf** の `read_sf()` 関数を使います。ファイルのパスは `here()` で与えられます。- 今回の場合、ファイルはRプロジェクトの "data"、"gis"、"shp" というサブフォルダに "sle_adm3.shp" として格納されています（詳細は [import and export]() と [R Projects]() のページを参照してください）。独自のファイルパスを設定してください。

2022-02-03 09:36 UTC, ironwest commented on new_pages/gis.Rmd
> +下の表は、インポートとクリーニング後のシェープファイルの様子です。<u>右側にスクロールして</u>、admin レベル0（国）、admin レベル1、admin レベル2、そして最後に admin レベル3の列があることがわかります。それぞれのレベルには、キャラクター名と固有の識別子「pcode」があります。たとえば、SL（Sierra Leone） →  04（Western） →L0410
下の表は、インポートし、クリーニングした後のシェープファイルの様子です。<u>右側にスクロールして</u>、admin レベル 0（国）、admin レベル 1、admin レベル 2、そして最後に admin レベル 3 の列があることがわかります。それぞれのレベルには、キャラクター名と固有の識別子「pcode」があります。たとえば、SL（Sierra Leone） →  04（Western） →L0410（Western Area Rural）-→L0040101（Koya Rural）のように、pcode は admin レベルが上がるごとに拡張されます。

2022-02-03 09:40 UTC, ironwest commented on new_pages/gis.Rmd
> +施設の位置を示す点のシェープファイルを `read_sf()` でインポートし、列名をクリーンにしてから、hospital、clinic、doctor のいずれかにタグ付けされた点だけを残すようにフィルタリングしました。
施設の位置を示す点のシェープファイルを `read_sf()` でインポートし、列名をクリーニングしてから、病院（"hospital"）、診療所（"clinic"）、医師（"doctor"） のいずれかのタグが付けられた点だけを残すように抽出しました。

2022-02-03 09:42 UTC, ironwest commented on new_pages/gis.Rmd
> +X-Y座標（経度・緯度、点）をプロットする最も簡単な方法は、この症例の場合、準備編で作成した `linelist_sf` オブジェクトから直接、点として描画することです。
X-Y座標（経度・緯度で表される点）をプロットする最も簡単な方法は、今回の場合、準備編で作成した `linelist_sf` オブジェクトから直接、点として描画することです。

2022-02-08 21:29 UTC, ironwest commented on new_pages/gis.Rmd
> +**次に**、<u>`st_join()`と *st_intersects* の結合タイプを使って、これらのバッファと症例（点）を交差させます。</u>これによって、バッファからのデータが、交差している点に結合されます。
**次に**、<u>`st_join()` の *st_intersects* 結合タイプを使って、これらのバッファと症例（点）を交差させます。</u>これによって、バッファからのデータが、交差している点に結合されます。

2022-02-08 21:32 UTC, ironwest commented on new_pages/gis.Rmd
> +3) `mutate()` を用いて、人口 10,000 人あたりの症例数を新しい列として計算する。
3) `mutate()` を用いて、人口 10,000 人あたりの症例数を新しい列として計算します。

2022-02-08 21:43 UTC, ironwest commented on new_pages/gis.Rmd
> +**spdep** パッケージで使用している `sle_adm3` データの行政区域ポリゴン間の隣接関係を定量化することができます。ここでは、<u>共辺または共点</u>隣接 (*queen* contiguity) を指定します。こちらは、地域がその境界に沿って少なくとも1つの点を共有していれば、隣り合っていることを意味します。この他には、<u>共点</u>隣接 (*rook*) を指定するこ
**spdep** パッケージで使用している `sle_adm3` データの行政区域ポリゴン間の隣接関係を定量化することができます。ここでは、<u>共点</u>隣接 (*queen* contiguity) を指定します。こちらは、地域がその境界に沿って少なくとも1つの点を共有していれば、隣り合っていることを意味します。この他には、<u>共辺</u>隣接 (*rook*) を指定することもできます。こちらは、地域がその境界に沿って境界縁を共有していれば、隣り合っていることを意味します。この違いは些細なことですが、この事例は不規則なポリゴンですので、場合によっては queen と rook の選択が影響を与えることもあります。

2022-02-08 21:44 UTC, ironwest commented on new_pages/gis.Rmd
> +sle_listw <- spdep::nb2listw(sle_nb)   # listw (list of weights) オブジェクトを作成 -- 後で使います
# listw (重みのリスト) オブジェクトを作成 -- 後で使います

2022-02-08 21:49 UTC, ironwest commented on new_pages/gis.Rmd
> +よく引用されるトブラーの地理学の第一法則では、「すべてのものは他のすべてのものに関係しているが、近くのものは遠くのものより関係している」とされています。疫学においては、ある地域における特定の健康結果のリスクは、遠くの地域よりも近隣の地域に類似していることを意味していることが多い。この概念は、「空間的自己相関」として正式に定義されています。これは、類似した値を持つ地理的フィーチャが空間的に集まって
よく引用されるトブラーの地理学の第一法則では、「すべてのものは他のすべてのものに関係しているが、近くのものは遠くのものより関係している」とされています。疫学においては、ある地域における特定の健康結果のリスクは、遠くの地域よりも近隣の地域に類似していることを意味していることが多いです。この概念は、「空間的自己相関」として正式に定義されています。これは、類似した値を持つ地理的フィーチャが空間的に集まっているという統計的特性です。空間的自己相関の統計的測定は、データにおける<u>空間的クラスタリングの程度を定量化</u>し、クラスタリングが発生する場所を特定し、データ内の異なる変数間の空間的自己相関の<u>共通パターンを特定</u>するために使用することができます。このセクションでは、空間的自己相関の一般的な測定方法とRでの計算方法について説明します。

2022-02-08 22:02 UTC, ironwest commented on new_pages/gis.Rmd
> +**Moran's I** - これは、ある地域での変数の値と、近隣の地域での同じ変数の値との間の相関のグローバルな要約統計です。Moran's I統計は、通常、-1から1の範囲です。0の値は、空間的な相関のパターンがないことを示し、1や-1に近い値は、それぞれ空間的な自己相関（似たような値が近くにある）や空間的な分散（似ていない値が近くにある）が強いことを示しています。
**Moran's I** - これは、ある地域での変数の値と、近隣の地域での同じ変数の値との間の相関のグローバルな要約統計です。通常、Moran's I 統計量は、-1 から 1 の範囲をとります。0 は、空間的な相関のパターンがないことを示し、1 や -1 に近い値は、それぞれ空間的な自己相関（似たような値が近くにある）や空間的なばらつき（似ていない値が近くにある）が強いことを示しています。

2022-02-08 22:07 UTC, ironwest commented on new_pages/gis.Rmd
> +**Local Moran's I** - 上で計算した（グローバルな）Moran's I 統計を分解することで、<u>局所的な</u>空間的な自己相関を識別することができ、データ内の特定のクラスターを識別することができます。この統計は、LISA（Local Indicator of Spatial Association）統計と呼ばれることもあり、個々の地域における空間的自己相関の程度を要約し
**Local Moran's I** - 上で計算した（グローバルな）Moran's I 統計を分解することで、<u>局所的な</u>空間的な自己相関を識別することができます。これを利用すると、データ内の特定のクラスターの識別を行うことができます。この統計は、LISA（Local Indicator of Spatial Association）統計量と呼ばれることもあり、個々の地域における空間的自己相関の程度を要約したものです。この値は、地図上の「ホット」と「コールド」な場所を見つけるのに役立ちます。

2022-02-08 22:08 UTC, ironwest commented on new_pages/gis.Rmd
> +例として、上で使用したエボラ出血熱の症例数に対して、**spdep** の `local_moran()` 関数を用いて、Local Moran's I を計算し、マップすることができます。
例として、上で使用したエボラ出血熱の症例数に対して、**spdep** の `local_moran()` 関数を用いて、Local Moran's I を計算し、地図上に描画することができます。

2022-02-08 22:11 UTC, ironwest commented on new_pages/gis.Rmd
> +**Getis-Ord Gi*** - これもホットスポット分析によく使われる統計です。この統計が人気である理由は、ArcGISのホットスポット分析ツールで使われていることに関係しています。この統計は、通常、近隣地域間の変数の値の差は正規分布に従うはずだという仮定に基づいています。このツールは、z-score アプローチを使用して、指定された変数の値が近隣の地域に比べて著しく高い（ホットスポット
**Getis-Ord Gi\*** - これもホットスポットの分析によく使われる統計です。この統計が人気である理由は、ArcGIS のホットスポット分析ツールで使われていることに関係しています。この統計は、通常、近隣地域間の変数の値の差は正規分布に従うはずだという仮定に基づいています。このツールは、z-score を利用したアプローチを用いて、指定された変数の値が近隣の地域に比べて著しく高い（ホットスポット）または著しく低い（コールドスポット）地域を特定します。

2022-02-08 22:13 UTC, ironwest commented on new_pages/gis.Rmd
> +上のとおり、Getis-Ord Gi* のマップは、先に作成した Local Moran's のマップとは若干異なっています。これは、これらの2つの統計量を計算するために使用される方法がわずかに異なることを反映しています。どちらを使用すべきかは、特定の事例とあなたが関心を持っているリサーチクエスチョンに依存します。
上のとおり、Getis-Ord Gi* のマップは、先に作成した Local Moran's の地図とは若干異なっています。これは、これらの2つの統計量を計算するために使用される方法がわずかに異なることを反映しています。どちらを使用すべきかは、特定の事例とあなたが関心を持っているリサーチクエスチョンに依存します。

2022-02-08 22:14 UTC, ironwest commented on new_pages/gis.Rmd
> +**Lee's L test** - これは、二変量の空間相関に関する統計的なテストです。与えられた変数 *x* の空間パターンが、*x* に空間的に関連すると仮定された別の変数 *y* の空間パターンに類似しているかどうかを検定することができます。
**Lee's L test** - これは、二変量の空間相関に関する統計的な検定です。与えられた変数 *x* の空間パターンが、*x* に空間的に関連すると仮定された別の変数 *y* の空間パターンに類似しているかどうかを検定することができます。

2022-02-08 22:28 UTC, ironwest requested changes
レビューを行いました。「てにをは」は原則直接直してあります。また、レビュアー間の協議の結果、グラフや地図の日本語表記を行わない方針となったため、それも直接修正してあります。
他、書き換えが望ましいと感じた部分はコメントで追加しているので、ご面倒をおかけして恐縮ですが、ご査収と変更対応いただけますと幸いです。

2022-02-09 07:11 UTC, babayoshihiko commented
承知いたしました。

2022-02-12 02:44 UTC, babayoshihiko commented on new_pages/gis.Rmd
> +シェープファイルをインポートするには、**sf** の `read_sf()` 関数を使います。ファイルのパスは `here()` で与えられます。- ここでは、Rプロジェクトの "data"、"gis"、"shp" というサブフォルダにファイル名 "sle_adm3.shp" として格納されています（詳細は [import and export] と [R Projects] のページを参照し
> シェープファイルをインポートするには、**sf** の `read_sf()` 関数を使います。ファイルのパスは `here()` で与えられます。- 今回の場合、ファイルはRプロジェクトの "data"、"gis"、"shp" というサブフォルダに "sle_adm3.shp" として格納されています（詳細は import and export と R Projects のページを参照してください）。独自のファイルパスを設定してください。

Should I used the internal links, using #importing and #r-projects tags as?

（詳細は [import and export](#importing) と [R Projects](#r-projects) のページを参照してください）

2022-02-12 03:33 UTC, babayoshihiko commented
レビュー内容を反映いたしました。

2022-03-17 21:37 UTC, ironwest approved these changes

2022-03-17 21:37 UTC, merged