Translated
appliedepi/epiRhandbook_jp pull request #53
Opened 2022-02-06 13:36 UTC by A-Fushimi

The translation of this section is completed.

2022-02-13 21:09 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +また、適切な重みを作成するために、サンプリング集団のデータをインポートしたいと考えます。このデータはさまざまな形式で作成できますが、以下のようにすることをお勧めします（エクセルに入力するだけでもよいです）。
適切な重みを作成するために、サンプルを取得した集団についてのデータをインポートしましょう。このデータの形式はいろいろなもので作成することが可能ですが、以下に表示するような形式にすることをお勧めします（これは、エクセルに直接入力して作成することも可能です）。

2022-02-13 21:12 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +クラスター調査の場合は、クラスターレベルで調査の重みを加えることができます。このデータを上記のように入力することができます。また、カウント数が少ない場合は、以下のように入力して2つの列を作ることもできます。いずれにしても、調査データと一致するクラスター識別子の列と、各クラスターの世帯数の列が必要になります。
クラスター調査の場合は、クラスターレベルで調査の重みを加えることが必要な場合もあります。このデータは上記のようにして読み込むことができます。あるいは、カウント数が少ない場合は、以下のように入力して2つの列を作ることもできます。いずれにしても、調査データと一致するクラスターを識別する列と、各クラスターが含む世帯数を表す列が必要になります。

2022-02-13 21:13 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +### データクリーニング {.unnumbered}
データの前処理

2022-02-13 21:16 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +日付列が適切な形式であることを以下で確認しています。他にもいくつかの方法がありますが（詳しくは[「日付の扱い方」](https://epirhandbook.com/working-with-dates.html)のページをご覧ください）、辞書を使って日付を定義するのが手っ取り早くて簡単です。
下では、日付列が適切な形式であることを以下で確認しています。他にもいくつかの方法がありますが（詳しくは[「日付の扱い方」]()のページをご覧ください）。辞書を使って日付を定義するのが手っ取り早くて簡単です。<!--working with dates へのリンクはまとめてこちらで対応します。-->

2022-02-13 21:22 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +上記のように、（調査の作成方法にもよりますが）各レベルのデータは、Koboから別のデータセットとしてエクスポートされます。この例では、世帯が1つのレベルで、その世帯内の個人が1つのレベルです。
上記のように、（調査票をどのように計画するかにもよりますが）各レベルのデータは、Kobo から別々のデータセットとしてエクスポートされます。今回の例では、世帯と、その世帯内の個人がそれぞれ 1 つのレベルとなっています。

2022-02-13 21:23 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +この2つのレベルは、一意の識別子で結ばれています。Koboのデータセットの場合、この変数は世帯レベルでは"\_index"であり、個人レベルでは"\_parent_index"と一致します。これにより、一致する個人ごとに世帯の新しい行が作成されます。詳細はハンドブックの[結合](https://epirhandbook.com/joining-data.html)の項を参照してください。
これら2つのレベルは、一意の識別子で紐づけられています。Kobo データセットの場合、この変数は世帯レベルでは "_index" であり、個人レベルでは "_parent_index" と一致します。これにより、一致する個人ごとに世帯の新しい行が作成されます。詳細はハンドブックの[結合]()の項を参照してください。

2022-02-13 21:26 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +死亡率調査では、対象期間の適切な死亡率を算出するために、各個人がその場所にどのくらいの期間いたのかを知りたいです。これはすべての調査に当てはまるわけではありませんが、特に死亡率調査の場合、移動する人々や避難している人々の間で頻繁に行われるため、重要です。
死亡率調査では、対象期間の適切な死亡率を算出するために、各個人がその場所にどのくらいの期間いたのかを知りたいです。これはすべての調査に当てはまるわけではありませんが、特に死亡率調査の場合は重要です。なぜなら、移動する人々や避難している人々の間で頻繁に行われる調査だからです。

2022-02-13 21:28 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +これは、リコール期間（質問に答える際に参加者に報告を求める期間）としても知られています。この期間を利用して、対象期間外の死亡が報告された場合など、不適切な日付を欠損に設定することができます。
これを行うためには、まず、対象期間を定義する必要があります。これは、リコール期間（質問に答える際に参加者に報告を求める期間）としても知られています。この期間を利用して、対象期間外の死亡が報告された場合など、不適切な日付を欠損に設定することができます。

2022-02-13 22:02 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +開始日：リコール期間内の最も早い到着イベント、リコール期間の開始日（事前に定義する）、または該当する場合はリコール開始後の日付（到着や出産など）
開始日：リコール期間内の適切なイベントの中で最も古い日付。リコール期間の開始日（事前に定義する）、または該当するイベントがある場合はリコール開始後の日付（例：到着や出産など）

2022-02-13 22:05 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +終了日：リコール期間内の最も早い適切な出発イベント、リコール期間の終了日のいずれか、または該当する場合はリコール終了前の日付（出発、死亡など）
終了日：リコール期間内の適切なイベント終了の中で最も新しい日付。リコール期間の終了日（事前に定義する）、または該当する場合はリコール終了までの日付（例：出発や死亡など）

2022-02-16 09:04 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +  ## ここでは、2つのデータセットの列の最後にテキストを追加している
ここでは、2つのデータセットの列の最後に接尾文字を追加している

2022-02-16 09:10 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +人口統計（または年齢-性別）ピラミッドは、調査対象者の分布を視覚化する簡単な方法です。また、調査の層別に年齢と性別の[記述表](https://epirhandbook.com/descriptive-tables.html)を作成することも検討する価値があります。ここでは、上で作成した調査設計オブジェクトを使用して、加重比例が可能な**apyramid**パッケージを使用して説明します。[人口
[人口統計ピラミッド](https://epirhandbook.com/demographic-pyramids-and-likert-scales.html)を作成するための他のオプションについては、ハンドブックのその章で詳しく説明しています。

↓

[人口統計ピラミッド](https://epirhandbook.com/demographic-pyramids-and-likert-scales.html)の章で、人口統計ピラミッドを作成するための他のオプションについて詳しく説明しています。

2022-02-16 21:21 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +  ## yで分割すると、開始と終了の組み合わせが可能となる
yで分割すると、可能性のある開始と終了の組み合わせを取得できる

2022-02-16 21:33 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +  ## 使用する機能とその機能を実現するための引数の状態（デザイン）
使用する関数とその関数の引数（デザイン）を指定する

2022-02-16 21:38 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +  ## 使用する機能とその機能を実現するための引数の状態（デザイン）
使用する関数とその関数の引数（デザイン）を指定する

2022-02-16 21:41 UTC, ironwest commented on new_pages/survey_analysis.Rmd
> +同様に、（死亡率のような）重み付けされた比率については、**survey**や**srvyr**パッケージを使うことができます。さらに、複数の変数を反復処理する関数（上記のものと同様）を書くこともできます。上記のように**gtsummary**のための関数を作ることもできますが、現在のところ内蔵の機能はありません。
重み付けされた比率（例えば死亡率のような）については同様に、**survey** や **srvyr** パッケージを使うことができます。さらに、複数の変数を反復処理する関数（上記のものと同様）を書くこともできます。上記のように **gtsummary** のための関数を作ることもできますが、現在のところ内蔵の機能はありません。

2022-02-16 21:52 UTC, ironwest requested changes
おまたせいたしました。
レビュー目的で行の微調整や改行を入れています。

「てにをは」や数文字の変更は直接内容を書き換えています。文章単位での変更はコメントをご確認ください。

お手数ですが、内容のご確認と修正の程、よろしくお願い申し上げます。

2022-07-21 12:35 UTC, ysaito8015 reviewed
@A-Fushimi 
@ironwest 
各位
意図せず変更されたファイルがコミットされているため、改めて PR を作成し直しました

2022-07-25 23:26 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +また、適切な重みを作成するために、サンプリング集団のデータをインポートしたいと考えます。このデータはさまざまな形式で作成できますが、以下のようにすることをお勧めします（エクセルに入力するだけでもよいです）。
反映しました

2022-07-25 23:27 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +クラスター調査の場合は、クラスターレベルで調査の重みを加えることができます。このデータを上記のように入力することができます。また、カウント数が少ない場合は、以下のように入力して2つの列を作ることもできます。いずれにしても、調査データと一致するクラスター識別子の列と、各クラスターの世帯数の列が必要になります。
反映しました

2022-07-25 23:28 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +### データクリーニング {.unnumbered}
セクション中に「データクリーニングと主要関数」章への参照があるため、”データの前処理（データクリーニング）”としました

2022-07-25 23:39 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +日付列が適切な形式であることを以下で確認しています。他にもいくつかの方法がありますが（詳しくは[「日付の扱い方」](https://epirhandbook.com/working-with-dates.html)のページをご覧ください）、辞書を使って日付を定義するのが手っ取り早くて簡単です。
”下では” と "以下では" が一文内で重複しているので、調整しました

2022-07-25 23:40 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +上記のように、（調査の作成方法にもよりますが）各レベルのデータは、Koboから別のデータセットとしてエクスポートされます。この例では、世帯が1つのレベルで、その世帯内の個人が1つのレベルです。
反映しました

2022-07-25 23:45 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +この2つのレベルは、一意の識別子で結ばれています。Koboのデータセットの場合、この変数は世帯レベルでは"\_index"であり、個人レベルでは"\_parent_index"と一致します。これにより、一致する個人ごとに世帯の新しい行が作成されます。詳細はハンドブックの[結合](https://epirhandbook.com/joining-data.html)の項を参照してください。
反映しました

2022-07-26 00:07 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +死亡率調査では、対象期間の適切な死亡率を算出するために、各個人がその場所にどのくらいの期間いたのかを知りたいです。これはすべての調査に当てはまるわけではありませんが、特に死亡率調査の場合、移動する人々や避難している人々の間で頻繁に行われるため、重要です。
文意と訳語の整理を行いました

"死亡率調査において、対象期間の適切な死亡率を算出するために、各個人が対象地域にどのくらいの期間、居住したかという情報が必要です。この居住に関する情報は、すべての調査に当てはまるわけではありませんが、特に死亡率調査の場合は重要です。なぜなら、移動人口や避難民人口を含んだ状況で頻繁に行われる調査だからです。"

2022-07-26 00:18 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +これは、リコール期間（質問に答える際に参加者に報告を求める期間）としても知られています。この期間を利用して、対象期間外の死亡が報告された場合など、不適切な日付を欠損に設定することができます。
代名詞、指示語を置き換え、想起期間について補足しました

"死亡率調査を行うためには、まず、対象期間を設定する必要があります。対象期間の設定は、想起期間（リコール期間、質問に答える際に参加者にその期間の健康状態を考慮して回答を求める期間）としても知られています。この期間を利用して、対象期間外の死亡が報告された場合など、不適切な日付を欠損値に設定できます。"

2022-07-26 00:28 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +開始日：リコール期間内の最も早い到着イベント、リコール期間の開始日（事前に定義する）、または該当する場合はリコール開始後の日付（到着や出産など）
反映しました

2022-07-26 00:32 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +終了日：リコール期間内の最も早い適切な出発イベント、リコール期間の終了日のいずれか、または該当する場合はリコール終了前の日付（出発、死亡など）
反映しました

2022-07-26 00:33 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +  ## ここでは、2つのデータセットの列の最後にテキストを追加している
反映しました

2022-07-26 00:34 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +人口統計（または年齢-性別）ピラミッドは、調査対象者の分布を視覚化する簡単な方法です。また、調査の層別に年齢と性別の[記述表](https://epirhandbook.com/descriptive-tables.html)を作成することも検討する価値があります。ここでは、上で作成した調査設計オブジェクトを使用して、加重比例が可能な**apyramid**パッケージを使用して説明します。[人口
反映しました

2022-07-26 00:36 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +  ## yで分割すると、開始と終了の組み合わせが可能となる
反映しました

2022-07-26 00:36 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +  ## 使用する機能とその機能を実現するための引数の状態（デザイン）
反映しました

2022-07-26 00:36 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +  ## 使用する機能とその機能を実現するための引数の状態（デザイン）
反映しました

2022-07-26 00:38 UTC, ysaito8015 commented on new_pages/survey_analysis.Rmd
> +同様に、（死亡率のような）重み付けされた比率については、**survey**や**srvyr**パッケージを使うことができます。さらに、複数の変数を反復処理する関数（上記のものと同様）を書くこともできます。上記のように**gtsummary**のための関数を作ることもできますが、現在のところ内蔵の機能はありません。
反映しました

2022-07-31 17:48 UTC, closed without merging

2022-07-31 17:49 UTC, ysaito8015 commented
https://github.com/appliedepi/epiRhandbook_jp/pull/71