41_reportfactory_nn_20210923
appliedepi/epiRhandbook_jp pull request #6
Opened 2021-09-28 12:00 UTC by ironwest

Japnaese Translation of chapter 41 "Reportfactory"

2021-09-30 19:41 UTC, ysaito8015 reviewed
Could you check these some lines? @ironwest

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +## 新しい「工場」
There are no parentheses at "factory" in original.  My suggestion is that use word "factory" as it is or "ファクトリー", because it is a technical term in using "reportfactory".

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +# これを実行すると現在のワーキングディレクトリに新しい「工場」が作成されます
There are no parentheses at "factory" in original.

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +新しい「工場」の中には、自動的にサブフォルダやファイルが作成されているはずです。
There are no parentheses at "factory" in original.

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +# 新しく作成された「工場」の初期ファイルやサブフォルダの画像。
There are no comments in original

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +* `path = ` - 新しい「工場」フォルダが作成されるパスを指定できます（初期設定は現在の作業ディレクトリ）
There are no parentheses at word "factory" in original.

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +これで準備が整いました。`factory_overview()`コマンドを実行すると、「工場の構造」（すべてのフォルダとファイル）を見ることができます。
There are no parentheses at words "structure in the factory" in original.

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +factory_overview()            # コンソールに「工場の構造」を表示する
There are no parenthesis at word "overview of the factory" in original.

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +次の図のように、「工場」に含まれるフォルダとファイルが R コンソールに表示されます。"data" フォルダの中に "raw" と "clean" サブフォルダと例示のための CSV データが含まれていることに注意してください。また、 "example_report.Rmd" ファイルが同じように "report_sources" フォルダに含まれています。
There are no parentheses at word "factory" in original.

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +# nn:画像の表示用。 factory_overview()の実行結果が表示されている。
There is no comment in original.

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +「工場 R プロジェクト」の中で、普段行うように R Markdown ファイルを作成して、"report_sources" フォルダに保存してみましょう。 R Markdown ファイルの作成方法は、[R Markdown][Reports with R Markdown]のページを参照してください。例示することを目的に、ここでは次のように「工場」を変更しています。
There are no parentheses at words "factory R project" and "factory" in original.

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +# nn:画像の表示用。 factory_overview()の実行結果と変更されているファイルがハイライトされている。
There is no comment in original

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +「レポート工場」では、R Markdown レポートを「コンパイル」するとは、 .Rmd スクリプトが実行され、出力結果が作成されるという意味となります。（出力結果は、YAML に記載されている通りとなり、例として HTML、Word、PDF などのファイル形式となります）
There are no parentheses at word "report factory" in original

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +* **reportfactory** では、関数 `list_deps()` を使用して、「工場」全体のレポートに必要なすべてのパッケージをリストアップすることができます。
There are no parentheses at word "factory" in original

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +``
It would be an accidental insert.

2021-09-30 19:41 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +* RStudio のセッションは、この「工場 R プロジェクト」に「移動」します。
There are no parentheses at words "the factory R project" in original.

2021-10-11 10:42 UTC, ironwest commented on new_pages/reportfactory.Rmd
> +## 新しい「工場」
Thanks. I will change all 工場 to ファクトリー

2021-10-12 00:43 UTC, ironwest reviewed
All 工場 changed to ファクトリー.
Comments not written in original contents are removed.

Thank you for another review.
追記：操作を間違えました。申し訳ありません。

2021-10-19 20:05 UTC, ysaito8015 requested changes

2021-10-19 20:05 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +作成するレポートが複数ある場合は、すべてのレポートに対する`compile_reports()`コマンドを含んだ R スクリプトを作成することを検討してください。ユーザーは、この R スクリプト内のすべてのコマンドを実行するだけで、すべてのレポートがコンパイルされます。この "run-file" を "scripts" フォルダに保存することができます。
it needs spaces before and after "`compile_reports()`"

2021-10-19 20:05 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +出力の一覧を確認するには、`list_outputs()`を使用してください。
it needs a space after "`list_outputs()`"

2021-10-19 20:05 UTC, ysaito8015 commented on new_pages/reportfactory.Rmd
> +必要であれば、"Knit" ボタンを押して、R Markdown レポートの1つを "Knit"することもできます。 "knit" した場合、デフォルトでは Rmd が保存されている、 "report_sources" フォルダに出力が表示されます。 以前のバージョンの **reportfactory** では、"report_sources" に Rmd 以外のファイルがあるとコンパイルができ
it needs a space after "レポートの1つを "Knit""

2022-07-19 03:44 UTC, ysaito8015 approved these changes
レビューが遅くなり申し訳ありません。
以下の点を変更しました。
ご確認をお願いします。


- ページ -> 章
- 他の章へのリンクを追加
- **abc** -> **abc** パッケージ
- 〜することができます -> 〜できます
- Rmd ファイル、Rmd レポート、Rmd スクリプトなどの表記のゆらぎを統一
-

2022-07-31 17:39 UTC, ysaito8015 approved these changes

2022-07-31 17:40 UTC, merged